### PR TITLE
Adapt project source files for using with Gradle in Android Studio

### PR DESCRIPTION
**Pull request by C-D-Lewis**
All files for AS added except Gradle binaries and build output, which should be sufficient. 

Tested and working.

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
ping @cjwilliams for review.

**Comment by sarfata** [comment]
Looks like code is getting duplicated between android studio and eclipse.

Why not follow the pattern that we have used for the other examples?

**Comment by C-D-Lewis** [comment]
For compatibility. Shall I make it Android Studio only and remove the Eclipse files?

**Comment by cjwilliams** [comment]
How do we feel about having master be Android Studio only and create an Eclipse only branch? We'd need to add to the README though.

**Comment by sarfata** [comment]
The other examples work for both (with the help of the doc). All our examples should follow the same organization.

**Comment by cjwilliams** [comment]
I agree that we should be consistent in our organization. However, we should attempt to be consistent using the best methodology, not necessarily what we have done in the past (subject to resource constraints, etc). Is clumping support for both editors in the same branch the best strategy?

**Comment by C-D-Lewis** [comment]
Two possibilities: 
- Pure source, relies on user knowing how to import to their IDE of choice. 
- Include both IDEs' project files. Makes import easier, but clutters the repo.

**Comment by cjwilliams** [comment]
I don't like idea #1, but idea #2 could be split into more granularity on how we do it. How does Google/Android handle this?

**Comment by cjwilliams** [comment]
"Note: At this time, the downloadable projects are designed for use with Gradle and Android Studio. Project downloads for Eclipse will be available soon!"

Source: http://developer.android.com/samples/index.html

**Comment by C-D-Lewis** [comment]
#2 is why there are two folders; 'Android Studio' and 'Eclipse'. But as Thomas said, there is code duplication.

**Pull request merged**
